#!/usr/bin/env zsh

#
# Zsh script for looping the command to automatically refresh the information
# Author: Jasper Haasdijk
#

while true
do
    clear
    printf "Fetched data from coinmarketcap.com at " && date +"%T"
    python3 main.py
    sleep 1200
done
